apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cream-config
  namespace: nginx-cream
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
data:
  example.conf: |
    server {
      listen 80;
      server_name localhost;
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }