apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cream
  namespace: nginx-cream
  labels:
    app: nginx-cream
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cream
  template:
    metadata:
      labels:
        app: nginx-cream
      annotations:
        checksum/config: {{ include "nginx-cream.configmapData" . | sha256sum }}
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.appVersion }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: example.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-cream-config-{{ .Values.appVersion }}
